Revamp pom.xml and change to version 0.8-SNAPSHOT * Fixes various shading issues with the SportPaper server * Updates intake to 1.2-SNAPSHOT, which fixes the /help is null bug * Rename output jars to be more descriptive * Downgrade text to 3.0.2, since 3.0.3 has a NoSuchMethodError
Signed-off-by: Ashcon Partovi <ashcon@partovi.net>